# config.yaml

model: "RULE"            # RULE (builtin) | MP_GESTURE | ONNX
frame_confirm: 5         # consecutive frames required
debounce_sec: 1        # min seconds between actions
angle_thresh: 8         # min fork angle (deg)

key_bindings:            # gesture label → key press
  V_SIGN: "right"        # next slide
  FIST:   "left"         # previous slide
  PALM:   "esc"          # exit slide show

hud:                     # heads-up display colours (BGR)
  text: [0, 255, 0]
  bar:  [255, 0, 0]
